# plot_inf.R: Plots the number of infections over time.
# This script uses the predictive posterior distributions generated by
# simulating posterior samples generated from prepare_post.R

# Clear the workspace.
rm(list = ls())

# Load in data manipulation and visualisation libraries.
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
library(gridExtra)

# Load in the default ggplot theme.
source("gg_theme.R")

# Define the folder of scenario testing outputs.
folder <- "../cpp/scenario_testing/out/scenario_free/"

# Load in the simulated data.
sim <- fread(paste0(folder, "simulation.csv"), header=TRUE, sep=",")

# Define the population size of each island.
pop <- data.frame("ISLAND_ID" = seq(0,3),
                  "POPULATION" = c(93616, 224353, 20052, 31872))

# Use to get dates corresponding to the times in the simulation.
dates <- fread("../data/ndvi.csv", header=TRUE, sep=",") %>%
  mutate(DATE = as.Date(DATE)) %>%
  filter(ISLAND_ID == 0)

# The last date we need is one week after the NDVI data finishes.
final_date <- data.frame("ISLAND_ID" = 0,
                         "WEEK" = (dates$WEEK[nrow(dates)] + 1) %% 4,
                         "MONTH" = (dates$MONTH[nrow(dates)] + (dates$WEEK[nrow(dates)] + 1) %/% 4 - 1) %% 12 + 1,
                         "YEAR" = dates$YEAR[nrow(dates)] + ((dates$MONTH[nrow(dates)] + (dates$WEEK[nrow(dates)] + 1) %/% 4 - 1) %/% 12)) %>%
  mutate(DAY = WEEK*7 + 1) %>%
  mutate(DATE = as.Date(paste(YEAR, sprintf("%.2d", MONTH), sprintf("%.2d", DAY)), format="%Y %m %d"))

# Append the final date and just extract dates and simulation times.
dates <- dates %>%
  bind_rows(final_date) %>%
  mutate(TIME = 0:(n()-1)) %>%
  ungroup() %>%
  select(TIME, DATE)

# Calculate the total number of infections at each time point.
infs <- group_by(sim, SAMPLE_ID, ISLAND_ID, TIME) %>%
  summarise(INFECTIONS = sum(E + I)/2) %>%
  left_join(dates, by="TIME") %>%
  left_join(pop, by="ISLAND_ID") %>%
  mutate(INFECTIONS = INFECTIONS*1000/POPULATION)

# Calculate the median and credible intervals.
inf_ci <- infs %>%
  group_by(ISLAND_ID, DATE) %>%
  summarise(Q_500 = quantile(INFECTIONS, probs=0.5),
            Q_250 = quantile(INFECTIONS, probs=0.25),
            Q_750 = quantile(INFECTIONS, probs=0.75),
            Q_975 = quantile(INFECTIONS, probs=0.975),
            Q_025 = quantile(INFECTIONS, probs=0.025))

# Define the names of each island based on their ID number.
facet_labels <- c("0" = "Anjouan",
                  "1" = "Grande Comore",
                  "2" = "Mayotte",
                  "3" = "Mohéli")

# Change the order of islands.
inf_ci$ISLAND_ID <- factor(inf_ci$ISLAND_ID, levels=c(1, 3, 0, 2))

# Plot the number of infections over time.
gg_inf <- ggplot(inf_ci, aes(x=DATE, colour=ISLAND_ID)) +
  geom_ribbon(aes(ymin=Q_025, ymax=Q_975, fill=ISLAND_ID, alpha="95_CI")) +
  geom_line(aes(y=Q_500, alpha="MED"), size=1) +
  geom_vline(xintercept=as.Date("2015-07-01"), linetype="dashed") +
  #geom_vline(xintercept=as.Date("2008-07-01"), linetype="dashed") +
  scale_x_date(date_breaks="1 year", date_labels="%Y") +
  scale_colour_brewer("Island", palette="Set1",
                      labels=facet_labels[levels(inf_ci$ISLAND_ID)]) +
  scale_fill_brewer("Island", palette="Set1",
                    labels=facet_labels) +
  scale_alpha_manual("Posterior distribution",
                     breaks=c("MED", "95_CI"),
                     labels=c("MED" = "Median", "95_CI" = "95% credible interval"),
                     values=c("MED" = 0.75, "95_CI" = 0.2)) +
  xlab("Calendar year") +
  ylab("Number of weekly infections\nper 1000 animals") +
  gg_theme +
  guides(colour=guide_legend(title.hjust=0, title.position="top", title.vjust=0,
                             override.aes=list(alpha=0.5)),
         alpha=guide_legend(title.hjust=0, title.position="top", title.vjust=0,
                            override.aes=list(linetype=c(1,0),
                                              fill=c(NA, "grey25"))))
print(gg_inf)

# Save and crop.
file_name <- "model_inf"
ggsave(filename=paste0(file_name, ".svg"), plot=gg_inf, width=16, height=6, dpi=600, scale=1,
       path="figures")
ggsave(filename=paste0(file_name, ".pdf"), plot=gg_inf, width=16, height=6, dpi=600, scale=1,
       path="figures")
system(paste0("bash -c \"pdfcrop --margin '14.22638' figures/", file_name, ".pdf figures/", file_name, ".pdf\""))
