# stat_r0_alt.R: Stats of the seasonal reproduction number and effective seasonal reproduction number.
# This script uses the predictive posterior distributions generated by simulating
# posterior samples from prepare_post.R.

# Clear the workspace.
rm(list = ls())

# Load in data manipulation and visualisation libraries.
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
library(gridExtra)

# Load in the default ggplot theme.
source("gg_theme.R")

# Define the folder of scenario testing outputs.
folder <- "../cpp/scenario_testing/out/scenario_free/"

# Load in posterior samples and the simulation data.
post <- fread(paste0(folder, "posterior.csv"), header=TRUE, sep=",")

# Load in the simulated data.
sim <- fread(paste0(folder, "simulation.csv"), header=TRUE, sep=",")

# Load in the NDVI data.
ndvi <- fread("../data/ndvi.csv", header=TRUE, sep=",") %>%
  mutate(ISLAND_ID = as.numeric(ISLAND_ID)) %>%
  mutate(DATE = as.Date(DATE)) %>%
  group_by(ISLAND_ID) %>%
  mutate(MIN_NDVI = min(NDVI)) %>%
  mutate(TIME = 0:(n()-1)) %>%
  ungroup()

# Calculate the proportion susceptible at each time point.
sim <- group_by(sim, SAMPLE_ID, ISLAND_ID, TIME) %>%
  summarise(PROP_S = sum(S) / sum(S + E + I + R),
            SERO_PREV = sum(R) / sum(S + E + I + R),
            INFECTIONS = sum(E + I)/2)

# Sample parameter sets that we have the simulated data for.
# In this case, that's all of them! Just spread out the parameters.
post <- post %>%
  spread(key=PAR_NAME, value=PAR_VALUE)

# Calculate the seasonal reproduction number.
rst <- dplyr::select(post, SAMPLE_ID, trans_scale_anj, trans_scale_gra, trans_scale_may, trans_scale_moh, ndvi_rate) %>%
  gather(key=ISLAND_ID, value=trans_scale, contains("trans_scale")) %>%
  mutate(ISLAND_ID = ifelse(ISLAND_ID == "trans_scale_anj", 0, ISLAND_ID)) %>%
  mutate(ISLAND_ID = ifelse(ISLAND_ID == "trans_scale_gra", 1, ISLAND_ID)) %>%
  mutate(ISLAND_ID = ifelse(ISLAND_ID == "trans_scale_may", 2, ISLAND_ID)) %>%
  mutate(ISLAND_ID = ifelse(ISLAND_ID == "trans_scale_moh", 3, ISLAND_ID)) %>%
  mutate(ISLAND_ID = as.numeric(ISLAND_ID)) %>%
  left_join(ndvi, by="ISLAND_ID") %>%
  left_join(sim, by=c("SAMPLE_ID", "ISLAND_ID", "TIME")) %>%
  mutate(RST = exp(ndvi_rate*(NDVI - MIN_NDVI) + trans_scale))

# Geometric mean function
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

# Calculate the number of weeks where RST > 1.
great_one_rst <- group_by(rst, SAMPLE_ID, ISLAND_ID, YEAR) %>%
  summarise(RST_GREAT_ONE = sum(RST > 1)) %>%
  group_by(SAMPLE_ID, ISLAND_ID) %>%
  summarise(RST_GREAT_ONE = mean(RST_GREAT_ONE)) %>%
  group_by(ISLAND_ID) %>%
  summarise(Q_500 = quantile(RST_GREAT_ONE/48*52, probs=0.5),
            Q_025 = quantile(RST_GREAT_ONE/48*52, probs=0.025),
            Q_975 = quantile(RST_GREAT_ONE/48*52, probs=0.975))

# Calculate the median maximum annual RST.
max_annual_rst <- group_by(rst, SAMPLE_ID, ISLAND_ID, YEAR) %>%
  summarise(RST_GREAT_ONE = max(RST)) %>%
  group_by(ISLAND_ID) %>%
  summarise(Q_500 = quantile(RST_GREAT_ONE/48*52, probs=0.5),
            Q_025 = quantile(RST_GREAT_ONE/48*52, probs=0.025),
            Q_975 = quantile(RST_GREAT_ONE/48*52, probs=0.975))

# Calculate the median minimum annual RST.
min_annual_rst <- group_by(rst, SAMPLE_ID, ISLAND_ID, YEAR) %>%
  summarise(RST_GREAT_ONE = min(RST)) %>%
  group_by(ISLAND_ID) %>%
  summarise(Q_500 = quantile(RST_GREAT_ONE/48*52, probs=0.5),
            Q_025 = quantile(RST_GREAT_ONE/48*52, probs=0.025),
            Q_975 = quantile(RST_GREAT_ONE/48*52, probs=0.975))

# Calculate the credible interval of the geometric mean.
geo_rst <- group_by(rst, SAMPLE_ID, ISLAND_ID) %>%
  summarise(GEO_RST = gm_mean(RST)) %>%
  group_by(ISLAND_ID) %>%
  summarise(Q_500 = quantile(GEO_RST, probs=0.5),
            Q_025 = quantile(GEO_RST, probs=0.025),
            Q_975 = quantile(GEO_RST, probs=0.975))

# Calculate the mean seasonal reproduction number for each island.
sum_rst <- group_by(rst, SAMPLE_ID, ISLAND_ID) %>%
  summarise(RST = mean(RST)) %>%
  group_by(ISLAND_ID) %>%
  summarise(Q_500 = quantile(RST, probs=0.5),
            Q_975 = quantile(RST, probs=0.975),
            Q_025 = quantile(RST, probs=0.025))
